---
- hosts: docker
  vars:
    username: mike
  gather_facts: no
  tasks:
  - name: ping
    ping:

  - name: install pre-reqs
    package:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    become: true

  - name: Add docker gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true

  - name: get release name
    command: lsb_release -cs
    register: release
    changed_when: false

  - name: Add repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"
      state: present
    become: true

  - name: Install docker
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
    become: true

  - name: Add user to the docker group
    user:
      name: "{{ username }}"
      append: yes
      groups: docker
    become: true
